apiVersion: v1
kind: Service
metadata:
  name: balbalm-feed
  namespace: devocean
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: balbalm-feed
  sessionAffinity: None
  type: ClusterIP
