name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build . \
          --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
          -t 147997130241.dkr.ecr.ap-northeast-2.amazonaws.com/balbalm/backend-feed:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.AWS_ECR_PASSWORD }}" | docker login --username AWS --password-stdin 147997130241.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Push Docker image
        run: |
          docker push 147997130241.dkr.ecr.ap-northeast-2.amazonaws.com/balbalm/backend-feed:latest
